name: jobapp
description: "job search app with node js backend"


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #ui

  flutter_screenutil: ^5.9.1
  getwidget: ^4.0.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  skeletonizer: ^1.1.2+1
  persistent_bottom_nav_bar: ^5.0.2
  sliver_app_bar_builder: ^1.1.0
  image_picker: ^1.1.1
  localstorage: ^5.0.0
  sliver_tools: ^0.2.12
  dotted_border: ^2.1.0
  smooth_page_indicator: ^1.1.0
  flutter_zoom_drawer: ^3.2.0

  #animation

  flutter_animate: ^4.5.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.2

  #state managment

  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get: ^4.6.6
  provider: ^6.1.2

  #graphs

  syncfusion_flutter_charts: ^25.2.4
  syncfusion_flutter_maps: ^25.2.4
  syncfusion_flutter_core: ^25.2.4

  #env
  flutter_dotenv: ^5.1.0
  shared_preferences: ^2.2.3

  #api
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:

  uses-material-design: true


  assets:
    - assets/ai/































